config/routes.rb
Joom::Application.routes.draw do

  root to: 'pages#index'

  resources :posts
  resources :blog, controller: :posts

  get '/who_is',       to: 'pages#who_is_dl'
  get '/issues',       to: 'pages#issues'

  get  '/sign_in',  to: 'sessions#new',     as: :sign_in
  post '/sign_in',  to: 'sessions#create',  as: :create_session
  get  '/sign_out', to: 'sessions#destroy', as: :sign_out

  get '/:topic',      to: 'pages#topics'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  include Authem::User
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable

  default_scope -> { order(created_at: :desc) }
  scope :published, -> { where(published: true) }

  validates :title, presence: true, uniqueness: true
  validates_length_of :blurbs, maximum: 25, too_long: "must be less 50 or fewer words"

  before_save :build_slug

  def build_slug
    self.slug = title.parameterize
  end

  def self.find_by_slug_or_id(param)
    where(["slug = ? OR id = ?", param, param.to_i]).first
  end

  private

  def blurbs
    blurb.scan(/\w+/)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  authem_for :admin
  protect_from_forgery

  decent_configuration { strategy DecentExposure::StrongParametersStrategy }

  def deny_admin_access
    redirect_to :sign_in unless admin_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  expose(:posts)            { show_posts             }
  expose(:about)            { load_markdown "about"  }
  expose(:intro)            { load_markdown "intro"  }
  expose(:issues)           { load_markdown "issues" }
  expose(:topic)            { params[:topic]         }
  expose(:latest)           { latest_post            }
  expose(:latest_post_path) { latest_post_path       }
  expose(:recent)           { recent_posts           }

  private

  def load_markdown(page_name)
    File.read("#{Rails.root}/app/views/pages/markdown/#{page_name}.md")
  end

  def show_posts
    available_posts = admin_signed_in? ? all_by_topic : published_by_topic
    paginate(available_posts)
  end

  def all_by_topic
    Post.all.tagged_with params[:topic]
  end

  def published_by_topic
    Post.published.tagged_with params[:topic]
  end

  def latest_post
    return {} if Post.published.presence.nil?
    Post.published.first
  end

  def latest_post_path
    return root_path if latest_post.empty?
    latest_post[:slug]
  end

  def recent_posts
    Post.published.order("created_at DESC").offset(1).first(limit = 3)
  end

  def paginate(available_posts)
    available_posts.paginate(page: params[:page], per_page: 2)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_admin, except: [:show]

  expose(:posts) { all_posts }
  expose(:topics) { topics }
  expose(:published_posts) { Post.published.presence || [] }
  expose(:post, finder: :find_by_slug_or_id, attributes: :post_attributes)

  def create
    post.tag_list.add(params["tag"]["name"])
    post.save ? redirect : error_and_retry(:new)
  end

  def update
    update_post_tag unless post.tag_list.first == params["tag"]["name"]
    post.save ? redirect : error_and_retry(:edit)
  end

  def destroy
    post.destroy!
    redirect_to :root 
  end

  private

  def topics
    topic_list = ActsAsTaggableOn::Tag.all.order(:name).map { |tag| tag.name }
    tag = post.tag_list.first
    return topic_list if tag.nil?
    topic_list.delete  tag
    topic_list.unshift tag
  end

  def error_and_retry(action)
    flash[:notice] = post.errors.messages
    render(action)
  end

  def redirect
    flash.clear if flash
    redirect_to root_path
  end

  def update_post_tag
    post.tag_list = []
    post.tag_list.add(params["tag"]["name"])
  end

  def all_posts
    available_posts = admin_signed_in? ? Post.all : published_posts
    paginate(available_posts)
  end

  def paginate(available_posts)
    available_posts.paginate(page: params[:page], per_page: 2)
  end

  def post_attributes
    params.require(:post).permit(:published, :body, :blurb, :title, :tag_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  expose(:admin) { Admin.where(email: params[:email].downcase).first }
  expose(:posts) { get_posts }
  expose(:published_posts) { Post.published.presence || [] }

  def create
    if admin && admin.authenticate(params[:password])
      sign_in(admin, remember: params[:remember])
      redirect_to :root
    else
      redirect_to :sign_in
    end
  end

  def destroy
    sign_out_admin
    redirect_to root_path
  end

  private

  def get_posts
    admin_signed_in? ? Post.all.presence || [] : published_posts
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_link_to(text, path, options={})
    link_to(text, path, options.merge({class: active?(path)}))
  end

  def active?(path)
    "active" if /^#{path}/ =~ request.path
  end
end

app/helpers/dummy_image_helper.rb
module DummyImageHelper
  def dummy_image(width, height, background=nil, text=nil)
    background = background ? "/#{background}" : ""
    text = text ? "/#{text}" : ""
    content_tag :img, nil, alt: "", "data-src" => "/placeholder/#{width}x#{height}#{background}#{text}"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def snip_body(text)
    snipped_text = Nokogiri::HTML(text).xpath("//text()").to_s
    snipped_text.scan(/\w+/)[0..50].join(' ') + '...'
  end
  def markdown(text)
    RDiscount.new(text, :footnotes).to_html.html_safe
  end
end

app/views/layouts/_copyright.html.haml
#copyright
  Design by:
  %a{:href => "http://html5up.net"} HTML5 UP

app/views/layouts/_navigation.html.haml
%nav#nav
  Post Topics
  %ul
    %li.topics= link_to 'Culture & Politics', '/culture'
    %li.topics= link_to 'Jacksonville', '/jacksonville'
    %li.topics= link_to 'Pesonal Development', '/development'
    %li.topics= link_to 'Technology & Code', '/technology'

app/views/layouts/_sidebar.html.haml
#sidebar
  %h1#logo
    = link_to 'DL', root_path
  = render 'layouts/who_is_dl'
  = render 'layouts/navigation'
  = render 'layouts/copyright'
  - if admin_signed_in?
    .admin_actions
      %p
        Admin Functions
      = link_to 'sign out', :sign_out
      = link_to '+ add post', :new_blog

app/views/layouts/_who_is_dl.html.haml
%nav#nav
  More About Me
  %ul
    %li.topics= link_to 'Who Am I?', :who_is
    -#%li.topics= link_to 'On The Issues', :issues

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JustOneOfMe 
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = yield :stylesheet
    = csrf_meta_tag
    %meta(name="viewport" content="width=device-width, initial-scale=1")
  %body
    = yield
    = render 'layouts/sidebar'

app/views/pages/_influences.html.haml
%div
  :markdown

app/views/pages/_outside_links.html.haml
.social-media
  %a{ href: "https://github.com/444c43" }
    .icon.fa-github-alt.fa-3x
  %a{ href: "http://twitter.com/2toneDL" }
    .icon.fa-twitter.fa-3x
  %a{ href: "https://www.strava.com/athletes/devdl" }
    .icon.fa-bicycle.fa-3x
  %a{ href: "https://www.linkedin.com/in/devdl" }
    .icon.fa-linkedin-square.fa-3x

app/views/pages/_purpose.html.haml
%div
  this blog's purpose...

app/views/pages/index.html.haml
#content
  .who_is
    = markdown intro
  = render 'outside_links'
  .latest-post Latest Post
  %article.latest
    %header
      %h2= link_to latest.title, blog_path(latest.slug)
    %p= latest.blurb

app/views/pages/issues.html.haml
#content
  = markdown issues

app/views/pages/topics.html.haml
#content
  %h3.title #{topic.capitalize} Posts
  %inner
    - posts.each do |post|
      %article.box.post.post-excerpt
        %header
          %h2= link_to post.title, blog_path(post.slug)
        .info
          %span.date
            %span.month= post.created_at.strftime('%b')
            %span.day= post.created_at.strftime('%d')
            %span.year= post.created_at.strftime('%Y')
        %p= post.blurb
  = render 'shared/pagination'

app/views/pages/who_is_dl.html.haml
#content
  .image_me
  = image_tag "me.png", size: "100x100"
  = markdown about

app/views/posts/_admin_links.html.haml
.admin
  = "*un-published" unless post.published
  = link_to 'edit', edit_blog_path(post.slug)
  = "-"
  = link_to 'delete', post_path(post.slug),
    method: :delete, data: { confirm: "You sure?" }

app/views/posts/_form.html.haml
%article.blog
  = render 'shared/flash_messages' if flash
  = form_for post do |f|
    .field= f.check_box_with_label :published, 'publish?'
    .label= 'Title'
    .field= f.text_field :title
    .label= 'Blurb'
    .field= f.text_field :blurb, onkeypress: "wordCount('#blurb_count ', '#post_blurb')"
    .label= 'Body'
    .field= f.text_area :body, onkeypress: "wordCount('#body_count ', '#post_body')"
    .field= select(:tag, :name, options_for_select(topics))
    %p#body_count
      Total Body Count:
      %span 0
    #blurb_count
      Total Blurb Count:
      %span 0
    .field= f.submit

app/views/posts/edit.html.haml
#content
  = render 'form', post: post

app/views/posts/index.html.haml
#content
  %inner
    - posts.each do |post|
      %article.box.post.post-excerpt
        %header
          %h2= link_to post.title, blog_path(post.slug)
        .info
          %span.date
            %span.month= post.created_at.strftime('%b')
            %span.day= post.created_at.strftime('%d')
            %span.year= post.created_at.strftime('%Y')
        %p= post.blurb
  = render 'shared/pagination'

app/views/posts/new.html.haml
#content
  = render 'form', post: post

app/views/posts/show.html.haml
#content
  .post
    = render 'admin_links' if admin_signed_in?
    %h1= post.title
    #post_date
      %span= post.created_at.strftime("%d%b%y")
    #post_tags
      %span= "Topic: #{post.tag_list[0]}"
    = markdown(post.body)
    %h2#comments Comments
    #disqus_thread
    :javascript
      var disqus_shortname = 'justoneofme';

      (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    %noscript
      Please enable JavaScript to view the
      %a{:href => "http://disqus.com/?ref_noscript"} comments powered by Disqus.
    %a.dsq-brlink{:href => "http://disqus.com"}
      blog comments powered by
      %span.logo-disqus Disqus

app/views/shared/_flash_messages.html.haml
#flash_messages
  - flash.each do |key, value|
    - value.each do |k, v|
      %p= k.to_s.capitalize + " #{v.first}"

app/views/shared/_pagination.html.haml
= will_paginate posts, :page_links => true if posts.count > 2
.page_info
  = page_entries_info posts unless posts.empty?